Update featured-dotgov.html
cisagov/get.gov pull request #292
Opened 2024-05-09 15:38 UTC by amcelya

Update featured .gov to everykidoutdoors.gov

## Changes

- Updates featured .gov from Read.gov to EveryKidOutdoors.gov
- Updates description to match new featured domain

## Context for reviewers

Please review the language and grammar to ensure it is functional, succinct, and correct. The original language can be found here:
[https://docs.google.com/document/d/1jkiWrB1YCdhTD85xWDzJhg3gb0Sk_HnXYg-2SjGeDko/edit]

2024-05-09 15:54 UTC, h-m-f-t requested changes
Suggesting a small change, but everything else looks good!

2024-05-09 15:54 UTC, h-m-f-t commented on _includes/featured-dotgov.html
> +        <a class="usa-link usa-link--external" rel="noopener noreferrer" href="https://everykidoutdoors.gov/index.htm">EveryKidOutdoors.gov</a>
https://everykidoutdoors.gov does redirect to the /index.htm page, but I think you should drop `/index.htm` from this href.

2024-05-15 15:59 UTC, amcelya reviewed
Changes made as requested

2024-05-15 16:00 UTC, amcelya reviewed
Changes made

2024-05-15 16:00 UTC, h-m-f-t approved these changes

2024-05-15 16:01 UTC, merged